### ISSUE TITLE
Where is the "snakemake_wrapper_utils installed directory"?

### ISSUE THREAD

**Issue by jhxaz** [dxsbiocc/Workflow#2]
Hi，
You mentioned "copy the file utils/base.py to package snakemake_wrapper_utils installed directory", I was confused by the description because Ido not know the path of "snakemake_wrapper_utils installed directory"? Do you mean the ./wrapper dir?
Could you please help me? 
Thanks

**Comment by dxsbiocc** [comment]
You con find this package using command 'pip show snakemake_wrapper_utils', if you install package through 'pip install snakemake_wrapper_utils'
